// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlZKO7QBennrTSEtAld9tfep0hoipiKD0',
    appId: '1:100106142192:web:0b3b407d937b37c4829d35',
    messagingSenderId: '100106142192',
    projectId: 'blingkis-pbb',
    authDomain: 'blingkis-pbb.firebaseapp.com',
    storageBucket: 'blingkis-pbb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA1g75Gbci9WGuQGgCQ2fM046iJmGfrpc',
    appId: '1:100106142192:android:05403c22cc95bb8c829d35',
    messagingSenderId: '100106142192',
    projectId: 'blingkis-pbb',
    storageBucket: 'blingkis-pbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDZ_1FD_dvoL6vyMViQ0OEcbElvFgBCDo',
    appId: '1:100106142192:ios:fe762e0881abb171829d35',
    messagingSenderId: '100106142192',
    projectId: 'blingkis-pbb',
    storageBucket: 'blingkis-pbb.firebasestorage.app',
    iosClientId: '100106142192-v47rpkabb3sakjof324npgv2l1qr1kge.apps.googleusercontent.com',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDZ_1FD_dvoL6vyMViQ0OEcbElvFgBCDo',
    appId: '1:100106142192:ios:fe762e0881abb171829d35',
    messagingSenderId: '100106142192',
    projectId: 'blingkis-pbb',
    storageBucket: 'blingkis-pbb.firebasestorage.app',
    iosClientId: '100106142192-v47rpkabb3sakjof324npgv2l1qr1kge.apps.googleusercontent.com',
    iosBundleId: 'com.example.projek',
  );
}
